pull_request_rules:
  - name: automatically merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - status-success=Continuous Integration
    actions:
      merge:
        method: merge
